image: node:16-alpine

stages:
  - test

.platform_job:
  tags:
    - platform

tests:
  stage: test
  extends: .platform_job
  image: mcr.microsoft.com/playwright/java
  before_script:
    - cat /etc/*-release
    - java -version
    - mvn -version
  script:
    - mvn clean test -DsuiteXmlFile='testng.xml'
  only:
    - develop