image: mcr.microsoft.com/playwright/java

stages:
  - uitest

.platform_job:
  tags:
    - platform

variables:
  accepted_rate:
    value: "95"
    description: "Accepted pass rate"

  testExecKey:
    description: "XRAY Test Execution Ticket ID"

tests:
  stage: uitest
  extends: .platform_job
  before_script:
    - cat /etc/*-release
    - java -version
    - mvn -version
  script:
    - echo "[Auto-Message] Start UI Test Cases execution"
    - mvn clean test -DsuiteXmlFile='testng.xml' -Dheadless=true
    - echo "[Auto-Message] UI Test Cases execution is done"
    - mvn io.qameta.allure:allure-maven:report
  artifacts:
    when: always
    paths:
      - /builds/cx_rnd/cx-platform/test-automation/target/site/allure-maven-plugin/*
      - /builds/cx_rnd/cx-platform/test-automation/target/surefire-reports/testng-results.xml
    expire_in: 1 week
  only:
    - develop

report:
  stage: uitest
  needs:
    - job: tests
      artifacts: true
  extends: .platform_job
  script:
    - mkdir public
    - mv $CI_PROJECT_DIR/target/site/allure-maven-plugin/* public
    - mv $CI_PROJECT_DIR/target/surefire-reports/testng-results.xml public
    - |
        if [ -n "$testExecKey" ]; then
          echo "[Auto-Message] Upload test result to testng..."
          export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$client_id\",\"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
          echo $token
          curl -v -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer $token" --data @"$CI_PROJECT_DIR/public/testng-results.xml" "https://xray.cloud.getxray.app/api/v2/import/execution/testng?projectKey=PLATFORM&testExecKey=$testExecKey"
          echo "[Auto-Message] Upload test resul is done"
        fi
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - public  

pages:
  stage: deploy
  extends: .platform_job
  when: always
  needs:
    - report
  script:
    - echo "publish allure report to getlab pages"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
