image: mcr.microsoft.com/playwright/java

stages:
  - uitest

.platform_job:
  tags:
    - platform

.download_history: &download_history
  after_script:
    - mkdir backup && cd backup || true
    - "curl -v --location --output report.zip --request GET \"https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/jobs/artifacts/develop/download?job=pages\" --header \"Authorization: Bearer ${CI_DEPLOY_TOKEN}\" || true"
    - pwd
    - ls
    - unzip report.zip
    - cd ../
    - (cp -r backup/public/history/ target/site/allure-maven-plugin/history) || true

variables:
  accepted_rate:
    value: "95"
    description: "Accepted pass rate"

  testExecKey:
    description: "XRAY Test Execution Ticket ID"

tests:
  stage: uitest
  extends: .platform_job
  before_script:
    - cat /etc/*-release
    - java -version
    - mvn -version
  script:
    - echo "[Auto-Message] Start UI Test Cases execution"
    - mvn clean test -DsuiteXmlFile='testng.xml' -Dheadless=true
    - echo "[Auto-Message] UI Test Cases execution is done"
    - mvn io.qameta.allure:allure-maven:report
  <<: *download_history
  artifacts:
    when: always
    paths:
      - /builds/cx_rnd/cx-platform/test-automation/target/site/allure-maven-plugin/*
      - /builds/cx_rnd/cx-platform/test-automation/target/surefire-reports/testng-results.xml
    expire_in: 1 week
  only:
    - develop

report:
  stage: uitest
  needs:
    - job: tests
      artifacts: true
  extends: .platform_job
  script:
    - mkdir public
    - mv $CI_PROJECT_DIR/target/site/allure-maven-plugin/* public
    - mv $CI_PROJECT_DIR/target/surefire-reports/testng-results.xml public
    - |
        if [ -n "$testExecKey" ]; then
          echo "[Auto-Message] Upload test result to testng..."
          export token=$(curl -H "Content-Type: application/json" -X POST --data "{ \"client_id\": \"$client_id\",\"client_secret\": \"$client_secret\" }" https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
          echo $token
          curl -v -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer $token" --data @"$CI_PROJECT_DIR/public/testng-results.xml" "https://xray.cloud.getxray.app/api/v2/import/execution/testng?projectKey=PLATFORM&testExecKey=$testExecKey"
          echo "[Auto-Message] Upload test resul is done"
        fi
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - public  

pages:
  stage: uitest
  extends: .platform_job
  when: always
  needs:
    - report
  script:
    - echo "publish allure report to getlab pages"
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - develop

verify:
  stage: uitest
  needs:
    - job: report
      artifacts: true
  extends: .platform_job
  before_script:
    - cat /etc/*-release
    - apt-get update -y
    - apt-get install -y xmlstarlet
  script:
    - failed=$(xmlstarlet sel -t -v "/testng-results/@failed" $CI_PROJECT_DIR/public/testng-results.xml)
    - passed=$(xmlstarlet sel -t -v "/testng-results/@passed" $CI_PROJECT_DIR/public/testng-results.xml)
    # - total=$(xmlstarlet sel -t -v "/testng-results/@total" $CI_PROJECT_DIR/public/testng-results.xml)
    - total=$((passed+failed))
    - pass_rate=$((passed*100/total))
    - echo "[Auto-Message] accepted rate is $accepted_rate , Pass rate is $pass_rate , Total TC is $total , Pass TC is $pass"
    - if [ $pass_rate -lt $accepted_rate ]; then echo "[Auto-Message] Failed UI Tests run below accepted pass rate"; exit 1; else echo "[Auto-Message] Success UI Tests run within accepted pass rate"; fi
