image: node:16-alpine

stages:
  - test
  # - report

.platform_job:
  tags:
    - platform

variables:
  accepted_rate:
    value: "95"

tests:
  stage: test
  extends: .platform_job
  image: mcr.microsoft.com/playwright/java
  before_script:
    - cat /etc/*-release
    - java -version
    - mvn -version
    - apt-get update -y
    - apt-get install -y xmlstarlet
  script:
    - echo "Start UI Test Cases execution"
    - mvn clean test -DsuiteXmlFile='testng.xml'
    - mvn io.qameta.allure:allure-maven:report
  after_script:
    - pass=$(xmlstarlet sel -t -v "/testng-results/@passed" /builds/cx_rnd/cx-platform/test-automation/target/surefire-reports/testng-results.xml)
    - echo "Pass TC is $pass"
    - total=$(xmlstarlet sel -t -v "/testng-results/@total" /builds/cx_rnd/cx-platform/test-automation/target/surefire-reports/testng-results.xml)
    - echo "Total TC is $total"
    - pass_rate=$((pass*100/total))
    - echo "Pass rate is $pass_rate"
    # - accepted_rate=80.00
    - echo "accepted rate is $accepted_rate"
    - echo "$pass_rate < $accepted_rate"
    - if [ $pass_rate -lt $accepted_rate ]; then exit 1; else echo "Success UI Tests run within accepted pass rate"; fi
  artifacts:
    when: always
    paths:
      - /builds/cx_rnd/cx-platform/test-automation/target/site/allure-maven-plugin
      - /builds/cx_rnd/cx-platform/test-automation/target/surefire-reports/testng-results.xml
    expire_in: 1 week
  only:
    - develop



# reporting:
#   stage: report
#   extends: .platform_job
#   only:
#     - develop
#   script:
#     - mkdir public
#     - mv target/allure-report/* public
#   artifacts:
#     when: always
#     paths:
#       - public
