testing:
  stage: test
  when: manual
  trigger:
    include:
      - local: test.yml
    strategy: depend


# reporting:
#   stage: report
#   extends: .platform_job
#   only:
#     - develop
#   script:
#     - mkdir public
#     - mv target/allure-report/* public
#   artifacts:
#     when: always
#     paths:
#       - public
